# Generated by Django 3.2.4 on 2022-06-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Aditya', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=50)),
                ('employee_middle_name', models.CharField(blank=True, max_length=50)),
                ('employee_last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('alternate_mobile_number', models.IntegerField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=50)),
                ('maritial_staus', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.user')),
            ],
        ),
    ]
