# Generated by Django 3.2.4 on 2022-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=50)),
                ('employee_middle_name', models.CharField(max_length=50)),
                ('employee_last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('mobile_number', models.IntegerField()),
                ('alternate_mobile_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=50)),
                ('maritial_staus', models.CharField(choices=[('M', 'Married'), ('N', 'Not Married')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
            ],
        ),
    ]
